# Generated by Django 4.1.3 on 2022-11-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listings_followed_alter_category_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='auction',
        ),
    ]
