# Generated by Django 4.1.3 on 2022-11-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listings_hbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='caution',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
