# Generated by Django 4.1.3 on 2022-11-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listings_caution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='cImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='caution',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
