# Generated by Django 4.1.3 on 2022-11-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='hBidder',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
