# Generated by Django 4.2.1 on 2023-06-16 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='repeattimes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='repeatupto',
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.DateField(default='2023-6-16', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes'),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat_wkd',
            field=models.CharField(default='5', max_length=7, verbose_name='repeat at which days of the week?'),
        ),
        migrations.AddField(
            model_name='event',
            name='repeatd',
            field=models.CharField(choices=[('frv', 'Forever'), ('spc', 'Specific number of times'), ('utl', 'Util')], default='frv', max_length=3, verbose_name='set repetition'),
        ),
        migrations.AddField(
            model_name='event',
            name='repeatnumber',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='number of repetitions'),
        ),
        migrations.AddField(
            model_name='event',
            name='repeatutil',
            field=models.DateField(default='2023-6-16', help_text='Format: year-month-day', verbose_name='Repeat util'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Event's description"),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='18:15', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=models.CharField(choices=[('nvr', 'never'), ('day', 'daily'), ('wek', 'weekly'), ('mth', 'monthly'), ('yea', 'yearly'), ('wkd', 'specific weekdays'), ('edv', 'every days')], default='nvr', max_length=3, verbose_name='set repetition'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='18:14', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name="Event's name"),
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, verbose_name="Event's name")),
                ('start_time', models.TimeField(default='18:14', help_text='Format: hour:minute', verbose_name='Starting time')),
                ('end_time', models.TimeField(default='18:15', help_text='Format: hour:minute', verbose_name='Ending time')),
                ('quick_description', models.TextField(blank=True, null=True, verbose_name='quick description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='detailed description')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name="task's Notes")),
                ('priority', models.CharField(choices=[('vh', 'very hight'), ('h', 'hight'), ('m', 'medium'), ('l', 'low')], default='m', max_length=2)),
                ('weekday', models.ForeignKey(choices=[('1', 'monday'), ('2', 'tuesday'), ('3', 'wednesday'), ('4', 'thursday'), ('5', 'friday'), ('6', 'saturday'), ('0', 'sunday')], default='5', on_delete=django.db.models.deletion.RESTRICT, related_name='Todaytask', to='appointment.weekday')),
            ],
        ),
    ]
