# Generated by Django 4.2.1 on 2023-06-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_event_end_time_alter_event_repeat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='18:27', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=models.CharField(choices=[('nvr', 'never'), ('day', 'daily'), ('wek', 'weekly'), ('mth', 'monthly'), ('yea', 'yearly'), ('wkd', 'specific weekdays')], default='nvr', max_length=3, verbose_name='when to repeat ?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_wkd',
            field=models.CharField(default='5', max_length=7, verbose_name='repeat at which days of the week? 0-6 / Sun-sat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='18:26', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(default='18:27', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(default='18:26', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
