# Generated by Django 4.2.1 on 2023-06-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_event_end_time_alter_event_repeat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='18:40', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='18:39', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(default='18:40', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(default='18:39', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='weekday',
        ),
        migrations.AddField(
            model_name='task',
            name='weekday',
            field=models.ManyToManyField(choices=[('1', 'monday'), ('2', 'tuesday'), ('3', 'wednesday'), ('4', 'thursday'), ('5', 'friday'), ('6', 'saturday'), ('0', 'sunday')], default='5', related_name='Todaytask', to='appointment.weekday'),
        ),
    ]
