# Generated by Django 4.1.3 on 2023-06-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_event_end_time_alter_event_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='whattotoday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Name')),
                ('day', models.DateField(default='2023-6-17', help_text='Format: year-month-day', verbose_name="Day i (don't) have to do it")),
                ('need', models.CharField(choices=[('Hv', 'Have to do today'), ('Dn', "Don't have to do today"), ('Bw', 'Big Win')], default='Hv', max_length=2)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(default='2023-6-17', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='13:21', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_wkd',
            field=models.CharField(default='6', max_length=7, verbose_name='repeat at which days of the week? 0-6 / Sun-sat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeatutil',
            field=models.DateField(default='2023-6-17', help_text='Format: year-month-day', verbose_name='Repeat util'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='13:20', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(default='13:21', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(default='13:20', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='weekday',
            field=models.ManyToManyField(choices=[('1', 'monday'), ('2', 'tuesday'), ('3', 'wednesday'), ('4', 'thursday'), ('5', 'friday'), ('6', 'saturday'), ('0', 'sunday')], default='6', related_name='Todaytask', to='appointment.weekday'),
        ),
    ]
