# Generated by Django 4.2.1 on 2023-06-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_whattotoday_alter_event_day_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(default='2023-6-19', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='12:26', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_wkd',
            field=models.CharField(default='1', max_length=7, verbose_name='repeat at which days of the week? 0-6 / Sun-sat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeatutil',
            field=models.DateField(default='2023-6-19', help_text='Format: year-month-day', verbose_name='Repeat util'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='12:25', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(default='12:26', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(default='12:25', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='weekday',
            field=models.ManyToManyField(related_name='Todaytask', to='appointment.weekday'),
        ),
        migrations.AlterField(
            model_name='whattotoday',
            name='day',
            field=models.DateField(default='2023-6-19', help_text='Format: year-month-day', verbose_name="Day i (don't) have to do it"),
        ),
        migrations.AlterField(
            model_name='whattotoday',
            name='need',
            field=models.CharField(choices=[('Hv', 'Have to do today'), ('Dn', "Don't have to do today"), ('Bw', 'Big Win'), ('Dl', 'Can delegate')], default='Hv', max_length=2),
        ),
    ]
