# Generated by Django 4.2.1 on 2023-06-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_event_day_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('vh', 'very hight'), ('h', 'hight'), ('m', 'medium'), ('l', 'low')], default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='12:33', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='12:32', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(default='12:33', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(default='12:32', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
