# Generated by Django 4.2.1 on 2023-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_alter_dailytask_end_time_alter_dailytask_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='weekday',
        ),
        migrations.AddField(
            model_name='weekday',
            name='todaytask',
            field=models.ManyToManyField(related_name='weekday', to='appointment.dailytask'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='end_time',
            field=models.TimeField(default='12:8', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='importance',
            field=models.CharField(choices=[('vh', 'very hight'), ('h', 'hight'), ('m', 'medium'), ('l', 'low')], default='m', max_length=2, verbose_name='How vital is this task ? Will It bring great benefits if done? Great demerits if not done?'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='start_time',
            field=models.TimeField(default='12:7', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='urgency',
            field=models.CharField(choices=[('vh', 'very hight'), ('h', 'hight'), ('m', 'medium'), ('l', 'low')], default='m', max_length=2, verbose_name='How urgent is this task ? Can it wait/be delayed?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(default='2023-6-27', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='12:8', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_wkd',
            field=models.ManyToManyField(blank=True, default='2', related_name='Todayevent', to='appointment.weekday'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeatutil',
            field=models.DateField(default='2023-6-27', help_text='Format: year-month-day', verbose_name='Repeat util'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='12:7', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='day',
            field=models.DateField(default='2023-6-27', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='Progress',
            field=models.CharField(choices=[('nt', 'Not Started'), ('st', 'Started'), ('ip', 'In Progress'), ('dn', 'Done'), ('fo', 'forgotten'), ('fn', 'forgottten and not started'), ('hd', 'Hardship')], default='nt', max_length=2, verbose_name="What's the progress on this task? "),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='day',
            field=models.DateField(default='2023-6-27', help_text='Format: year-month-day', verbose_name="the day i (don't) have to do this"),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='end_time',
            field=models.TimeField(default='12:8', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='need',
            field=models.CharField(choices=[('Hv', 'Have to do today'), ('Dn', "Don't have to do today"), ('Bw', 'Big Win'), ('Dl', 'Can delegate'), ('it', 'If enough time')], default='Hv', max_length=2),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='start_time',
            field=models.TimeField(default='12:7', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
