# Generated by Django 4.2.1 on 2023-06-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_rename_name_listtodo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='end_time',
            field=models.TimeField(default='17:54', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='start_time',
            field=models.TimeField(default='17:53', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='17:54', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='17:53', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='steps',
            field=models.ManyToManyField(blank=True, related_name='bigtask', to='appointment.listtodo'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='end_time',
            field=models.TimeField(default='17:54', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='start_time',
            field=models.TimeField(default='17:53', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
