# Generated by Django 4.1.3 on 2023-07-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0021_rename_name_whattodotoday_name_dailytask_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrepetiton',
            name='end_time',
            field=models.TimeField(default='20:20', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AddField(
            model_name='eventrepetiton',
            name='start_time',
            field=models.TimeField(default='20:19', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AddField(
            model_name='whattodotoday',
            name='color',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Color in the planner'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='end_time',
            field=models.TimeField(default='20:20', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='start_time',
            field=models.TimeField(default='20:19', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(default='2023-7-10', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='20:20', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_wkd',
            field=models.ManyToManyField(blank=True, default='1', related_name='Todayevent', to='appointment.weekday'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeatutil',
            field=models.DateField(default='2023-7-10', help_text='Format: year-month-day', verbose_name='Repeat util'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='20:19', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='day',
            field=models.DateField(default='2023-7-10', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='day',
            field=models.DateField(default='2023-7-10', help_text='Format: year-month-day', verbose_name="the day i (don't) have to do this"),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='end_time',
            field=models.TimeField(default='20:20', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='start_time',
            field=models.TimeField(default='20:19', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
