# Generated by Django 4.1.3 on 2023-07-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0027_datetracking_alter_dailytask_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='end_time',
            field=models.TimeField(default='21:22', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='importance',
            field=models.CharField(choices=[('vh', 'Essential'), ('h', 'important'), ('m', 'desirable'), ('l', 'Curiosity/interest'), ('vl', 'trivial'), ('cr', 'circumstantial')], default='m', max_length=2, verbose_name='How vital is this task ? Will It bring great benefits if done? Great demerits if not done?'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='start_time',
            field=models.TimeField(default='21:21', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='urgency',
            field=models.CharField(choices=[('vh', 'Essential'), ('h', 'important'), ('m', 'desirable'), ('l', 'Curiosity/interest'), ('vl', 'trivial'), ('cr', 'circumstantial')], default='m', max_length=2, verbose_name='How urgent is this task ? Can it wait/be delayed?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(default='2023-7-21', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='21:22', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='importance',
            field=models.CharField(choices=[('vh', 'Essential'), ('h', 'important'), ('m', 'desirable'), ('l', 'Curiosity/interest'), ('vl', 'trivial'), ('cr', 'circumstantial')], default='m', max_length=2, verbose_name='How vital is this event ? will It bring great benefits if done? Great demerits if not done?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_wkd',
            field=models.ManyToManyField(blank=True, default='5', related_name='Todayevent', to='appointment.weekday'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeatutil',
            field=models.DateField(blank=True, default='2023-7-21', help_text='Format: year-month-day', null=True, verbose_name='Repeat util'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='21:21', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='day',
            field=models.DateField(default='2023-7-21', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='end_time',
            field=models.TimeField(default='21:22', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='start_time',
            field=models.TimeField(default='21:21', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='importance',
            field=models.CharField(choices=[('vh', 'Essential'), ('h', 'important'), ('m', 'desirable'), ('l', 'Curiosity/interest'), ('vl', 'trivial'), ('cr', 'circumstantial')], default='m', max_length=2, verbose_name='How vital is this task ? will It bring great benefits if done? Great demerits if not done?'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='urgency',
            field=models.CharField(choices=[('vh', 'Essential'), ('h', 'important'), ('m', 'desirable'), ('l', 'Curiosity/interest'), ('vl', 'trivial'), ('cr', 'circumstantial')], default='m', max_length=2, verbose_name='How urgent is this task ? can it wait/be delayed?'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='day',
            field=models.DateField(default='2023-7-21', help_text='Format: year-month-day', verbose_name="the day i (don't) have to do this"),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='end_time',
            field=models.TimeField(default='21:22', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='start_time',
            field=models.TimeField(default='21:21', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
