# Generated by Django 4.1.3 on 2023-08-28 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0031_eventtool_alter_dailytask_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='end_time',
            field=models.TimeField(default='20:0', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='start_time',
            field=models.TimeField(default='19:59', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(choices=[(datetime.time(5, 15), datetime.time(5, 15)), (datetime.time(5, 30), datetime.time(5, 30)), (datetime.time(5, 45), datetime.time(5, 45)), (datetime.time(6, 0), datetime.time(6, 0)), (datetime.time(6, 15), datetime.time(6, 15)), (datetime.time(6, 30), datetime.time(6, 30)), (datetime.time(6, 45), datetime.time(6, 45)), (datetime.time(7, 0), datetime.time(7, 0)), (datetime.time(7, 15), datetime.time(7, 15)), (datetime.time(7, 30), datetime.time(7, 30)), (datetime.time(7, 45), datetime.time(7, 45)), (datetime.time(8, 0), datetime.time(8, 0)), (datetime.time(8, 15), datetime.time(8, 15)), (datetime.time(8, 30), datetime.time(8, 30)), (datetime.time(8, 45), datetime.time(8, 45)), (datetime.time(9, 0), datetime.time(9, 0)), (datetime.time(9, 15), datetime.time(9, 15)), (datetime.time(9, 30), datetime.time(9, 30)), (datetime.time(9, 45), datetime.time(9, 45)), (datetime.time(10, 0), datetime.time(10, 0)), (datetime.time(10, 15), datetime.time(10, 15)), (datetime.time(10, 30), datetime.time(10, 30)), (datetime.time(10, 45), datetime.time(10, 45)), (datetime.time(11, 0), datetime.time(11, 0)), (datetime.time(11, 15), datetime.time(11, 15)), (datetime.time(11, 30), datetime.time(11, 30)), (datetime.time(11, 45), datetime.time(11, 45)), (datetime.time(12, 0), datetime.time(12, 0)), (datetime.time(12, 15), datetime.time(12, 15)), (datetime.time(12, 30), datetime.time(12, 30)), (datetime.time(12, 45), datetime.time(12, 45)), (datetime.time(13, 0), datetime.time(13, 0)), (datetime.time(13, 15), datetime.time(13, 15)), (datetime.time(13, 30), datetime.time(13, 30)), (datetime.time(13, 45), datetime.time(13, 45)), (datetime.time(14, 0), datetime.time(14, 0)), (datetime.time(14, 15), datetime.time(14, 15)), (datetime.time(14, 30), datetime.time(14, 30)), (datetime.time(14, 45), datetime.time(14, 45)), (datetime.time(15, 0), datetime.time(15, 0)), (datetime.time(15, 15), datetime.time(15, 15)), (datetime.time(15, 30), datetime.time(15, 30)), (datetime.time(15, 45), datetime.time(15, 45)), (datetime.time(16, 0), datetime.time(16, 0)), (datetime.time(16, 15), datetime.time(16, 15)), (datetime.time(16, 30), datetime.time(16, 30)), (datetime.time(16, 45), datetime.time(16, 45)), (datetime.time(17, 0), datetime.time(17, 0)), (datetime.time(17, 15), datetime.time(17, 15)), (datetime.time(17, 30), datetime.time(17, 30)), (datetime.time(17, 45), datetime.time(17, 45)), (datetime.time(18, 0), datetime.time(18, 0)), (datetime.time(18, 15), datetime.time(18, 15)), (datetime.time(18, 30), datetime.time(18, 30)), (datetime.time(18, 45), datetime.time(18, 45)), (datetime.time(19, 0), datetime.time(19, 0)), (datetime.time(19, 15), datetime.time(19, 15)), (datetime.time(19, 30), datetime.time(19, 30)), (datetime.time(19, 45), datetime.time(19, 45)), (datetime.time(20, 0), datetime.time(20, 0)), (datetime.time(20, 15), datetime.time(20, 15)), (datetime.time(20, 30), datetime.time(20, 30)), (datetime.time(20, 45), datetime.time(20, 45)), (datetime.time(21, 0), datetime.time(21, 0)), (datetime.time(21, 15), datetime.time(21, 15)), (datetime.time(21, 30), datetime.time(21, 30)), (datetime.time(21, 45), datetime.time(21, 45)), (datetime.time(22, 0), datetime.time(22, 0)), (datetime.time(22, 15), datetime.time(22, 15)), (datetime.time(22, 30), datetime.time(22, 30)), (datetime.time(22, 45), datetime.time(22, 45)), (datetime.time(23, 0), datetime.time(23, 0)), (datetime.time(23, 15), datetime.time(23, 15)), (datetime.time(23, 30), datetime.time(23, 30)), (datetime.time(23, 45), datetime.time(23, 45))], verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_wkd',
            field=models.ManyToManyField(default=3, related_name='Todayevent', to='appointment.weekday'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeatnumber',
            field=models.IntegerField(default=1, verbose_name='number of repetitions'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeatutil',
            field=models.DateField(blank=True, help_text='Format: year-month-day', null=True, verbose_name='Repeat util'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(5, 0), datetime.time(5, 0)), (datetime.time(5, 15), datetime.time(5, 15)), (datetime.time(5, 30), datetime.time(5, 30)), (datetime.time(5, 45), datetime.time(5, 45)), (datetime.time(6, 0), datetime.time(6, 0)), (datetime.time(6, 15), datetime.time(6, 15)), (datetime.time(6, 30), datetime.time(6, 30)), (datetime.time(6, 45), datetime.time(6, 45)), (datetime.time(7, 0), datetime.time(7, 0)), (datetime.time(7, 15), datetime.time(7, 15)), (datetime.time(7, 30), datetime.time(7, 30)), (datetime.time(7, 45), datetime.time(7, 45)), (datetime.time(8, 0), datetime.time(8, 0)), (datetime.time(8, 15), datetime.time(8, 15)), (datetime.time(8, 30), datetime.time(8, 30)), (datetime.time(8, 45), datetime.time(8, 45)), (datetime.time(9, 0), datetime.time(9, 0)), (datetime.time(9, 15), datetime.time(9, 15)), (datetime.time(9, 30), datetime.time(9, 30)), (datetime.time(9, 45), datetime.time(9, 45)), (datetime.time(10, 0), datetime.time(10, 0)), (datetime.time(10, 15), datetime.time(10, 15)), (datetime.time(10, 30), datetime.time(10, 30)), (datetime.time(10, 45), datetime.time(10, 45)), (datetime.time(11, 0), datetime.time(11, 0)), (datetime.time(11, 15), datetime.time(11, 15)), (datetime.time(11, 30), datetime.time(11, 30)), (datetime.time(11, 45), datetime.time(11, 45)), (datetime.time(12, 0), datetime.time(12, 0)), (datetime.time(12, 15), datetime.time(12, 15)), (datetime.time(12, 30), datetime.time(12, 30)), (datetime.time(12, 45), datetime.time(12, 45)), (datetime.time(13, 0), datetime.time(13, 0)), (datetime.time(13, 15), datetime.time(13, 15)), (datetime.time(13, 30), datetime.time(13, 30)), (datetime.time(13, 45), datetime.time(13, 45)), (datetime.time(14, 0), datetime.time(14, 0)), (datetime.time(14, 15), datetime.time(14, 15)), (datetime.time(14, 30), datetime.time(14, 30)), (datetime.time(14, 45), datetime.time(14, 45)), (datetime.time(15, 0), datetime.time(15, 0)), (datetime.time(15, 15), datetime.time(15, 15)), (datetime.time(15, 30), datetime.time(15, 30)), (datetime.time(15, 45), datetime.time(15, 45)), (datetime.time(16, 0), datetime.time(16, 0)), (datetime.time(16, 15), datetime.time(16, 15)), (datetime.time(16, 30), datetime.time(16, 30)), (datetime.time(16, 45), datetime.time(16, 45)), (datetime.time(17, 0), datetime.time(17, 0)), (datetime.time(17, 15), datetime.time(17, 15)), (datetime.time(17, 30), datetime.time(17, 30)), (datetime.time(17, 45), datetime.time(17, 45)), (datetime.time(18, 0), datetime.time(18, 0)), (datetime.time(18, 15), datetime.time(18, 15)), (datetime.time(18, 30), datetime.time(18, 30)), (datetime.time(18, 45), datetime.time(18, 45)), (datetime.time(19, 0), datetime.time(19, 0)), (datetime.time(19, 15), datetime.time(19, 15)), (datetime.time(19, 30), datetime.time(19, 30)), (datetime.time(19, 45), datetime.time(19, 45)), (datetime.time(20, 0), datetime.time(20, 0)), (datetime.time(20, 15), datetime.time(20, 15)), (datetime.time(20, 30), datetime.time(20, 30)), (datetime.time(20, 45), datetime.time(20, 45)), (datetime.time(21, 0), datetime.time(21, 0)), (datetime.time(21, 15), datetime.time(21, 15)), (datetime.time(21, 30), datetime.time(21, 30)), (datetime.time(21, 45), datetime.time(21, 45)), (datetime.time(22, 0), datetime.time(22, 0)), (datetime.time(22, 15), datetime.time(22, 15)), (datetime.time(22, 30), datetime.time(22, 30)), (datetime.time(22, 45), datetime.time(22, 45)), (datetime.time(23, 0), datetime.time(23, 0)), (datetime.time(23, 15), datetime.time(23, 15)), (datetime.time(23, 30), datetime.time(23, 30))], verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='day',
            field=models.DateField(default='2023-8-28', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='end_time',
            field=models.TimeField(default='20:0', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='start_time',
            field=models.TimeField(default='19:59', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='day',
            field=models.DateField(default='2023-8-28', help_text='Format: year-month-day', verbose_name="the day i (don't) have to do this"),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='end_time',
            field=models.TimeField(default='20:0', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='start_time',
            field=models.TimeField(default='19:59', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
