# Generated by Django 4.1.3 on 2023-08-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0032_alter_dailytask_end_time_alter_dailytask_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='wednesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='end_time',
            field=models.TimeField(default='20:37', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='start_time',
            field=models.TimeField(default='20:36', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='end_time',
            field=models.TimeField(default='20:37', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='start_time',
            field=models.TimeField(default='20:36', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='end_time',
            field=models.TimeField(default='20:37', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='start_time',
            field=models.TimeField(default='20:36', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
