# Generated by Django 4.1.3 on 2023-09-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0033_event_friday_event_monday_event_saturday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='end_time',
            field=models.TimeField(default='20:44', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='start_time',
            field=models.TimeField(default='20:43', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='friday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='monday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_wkd',
            field=models.ManyToManyField(blank=True, related_name='Todayevent', to='appointment.weekday'),
        ),
        migrations.AlterField(
            model_name='event',
            name='saturday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='sunday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='thursday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='tuesday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='wednesday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='day',
            field=models.DateField(default='2023-9-15', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='end_time',
            field=models.TimeField(default='20:44', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='start_time',
            field=models.TimeField(default='20:43', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='day',
            field=models.DateField(default='2023-9-15', help_text='Format: year-month-day', verbose_name="the day i (don't) have to do this"),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='end_time',
            field=models.TimeField(default='20:44', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='start_time',
            field=models.TimeField(default='20:43', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
