# Generated by Django 4.1.3 on 2023-09-19 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0038_listtodo_step_alter_dailytask_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtodo',
            name='urgency_close_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Update to close when deadline is within:'),
        ),
        migrations.AddField(
            model_name='listtodo',
            name='urgency_close_type',
            field=models.CharField(choices=[('dy', 'Days'), ('wk', 'Weeks'), ('mh', 'Months'), ('yr', 'Years')], default='wk', max_length=2),
        ),
        migrations.AddField(
            model_name='listtodo',
            name='urgency_far_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Update to far when deadline is within:'),
        ),
        migrations.AddField(
            model_name='listtodo',
            name='urgency_far_type',
            field=models.CharField(choices=[('dy', 'Days'), ('wk', 'Weeks'), ('mh', 'Months'), ('yr', 'Years')], default='yr', max_length=2),
        ),
        migrations.AddField(
            model_name='listtodo',
            name='urgency_medium_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Update to medium when deadline is within:'),
        ),
        migrations.AddField(
            model_name='listtodo',
            name='urgency_medium_type',
            field=models.CharField(choices=[('dy', 'Days'), ('wk', 'Weeks'), ('mh', 'Months'), ('yr', 'Years')], default='mh', max_length=2),
        ),
        migrations.AddField(
            model_name='listtodo',
            name='urgency_update',
            field=models.BooleanField(default=False, verbose_name='Want this urgency to auto update as the deadline gets closer ?'),
        ),
        migrations.AddField(
            model_name='listtodo',
            name='urgency_veryclose_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Update to Very close when deadline is within:'),
        ),
        migrations.AddField(
            model_name='listtodo',
            name='urgency_veryclose_type',
            field=models.CharField(choices=[('dy', 'Days'), ('wk', 'Weeks'), ('mh', 'Months'), ('yr', 'Years')], default='dy', max_length=2),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='end_time',
            field=models.TimeField(default='20:57', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='start_time',
            field=models.TimeField(default='20:56', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='end_time',
            field=models.TimeField(default='20:57', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='start_time',
            field=models.TimeField(default='20:56', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='end_time',
            field=models.TimeField(default='20:57', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='start_time',
            field=models.TimeField(default='20:56', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
