# Generated by Django 4.1.3 on 2023-09-21 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0039_listtodo_urgency_close_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='end_time',
            field=models.TimeField(default='20:35', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='start_time',
            field=models.TimeField(default='20:34', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='day',
            field=models.DateField(default='2023-9-21', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='end_time',
            field=models.TimeField(default='20:35', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='start_time',
            field=models.TimeField(default='20:34', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='deadline_date',
            field=models.DateField(blank=True, default='2023-9-21', help_text='Format: year-month-day', null=True, verbose_name='When is the deadline?'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='progress',
            field=models.CharField(choices=[('nt', 'Not Started'), ('ip', 'In Progress'), ('dn', 'Done'), ('fo', 'forgotten'), ('fn', 'forgotten and not started'), ('hd', 'Hardship')], default='nt', max_length=2, verbose_name="What's the progress on this task? "),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='urgency',
            field=models.CharField(choices=[('vh', 'Very Close'), ('h', 'close'), ('m', 'Medium'), ('l', 'far'), ('vl', 'Very far')], default='m', max_length=2, verbose_name='How urgent is this task? can it wait/be delayed?'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='urgency_close_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Update to "close" when deadline is within:'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='urgency_close_type',
            field=models.CharField(choices=[('nn', '---------'), ('dy', 'Day(s)'), ('wk', 'Week(s)'), ('mh', 'Month(s)'), ('yr', 'Year(s)')], default='wk', max_length=2),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='urgency_far_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Update to "far" when deadline is within:'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='urgency_far_type',
            field=models.CharField(choices=[('nn', '---------'), ('dy', 'Day(s)'), ('wk', 'Week(s)'), ('mh', 'Month(s)'), ('yr', 'Year(s)')], default='yr', max_length=2),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='urgency_medium_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Update to "medium" when deadline is within:'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='urgency_medium_type',
            field=models.CharField(choices=[('nn', '---------'), ('dy', 'Day(s)'), ('wk', 'Week(s)'), ('mh', 'Month(s)'), ('yr', 'Year(s)')], default='mh', max_length=2),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='urgency_update',
            field=models.BooleanField(default=False, verbose_name='Want this urgency to auto update as the deadline gets closer?'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='urgency_veryclose_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Update to "very close" when deadline is within:'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='urgency_veryclose_type',
            field=models.CharField(choices=[('nn', '---------'), ('dy', 'Day(s)'), ('wk', 'Week(s)'), ('mh', 'Month(s)'), ('yr', 'Year(s)')], default='dy', max_length=2),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='day',
            field=models.DateField(default='2023-9-21', help_text='Format: year-month-day', verbose_name="the day i (don't) have to do this"),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='end_time',
            field=models.TimeField(default='20:35', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='start_time',
            field=models.TimeField(default='20:34', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
