# Generated by Django 4.1.3 on 2023-10-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0044_rename_steps_to_listtodo_step_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name="Event's description"),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='end_time',
            field=models.TimeField(default='19:12', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='start_time',
            field=models.TimeField(default='19:11', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='day',
            field=models.DateField(default='2023-10-20', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='end_time',
            field=models.TimeField(default='19:12', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='start_time',
            field=models.TimeField(default='19:11', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='duration',
            field=models.CharField(choices=[('mi', 'Minutes'), ('hs', 'Hours'), ('ds', 'Days'), ('wk', 'Weeks'), ('mn', 'Months'), ('ys', 'Years'), ('Pe', 'Perpetual')], default='hs', max_length=2, verbose_name='How long do you expect this to take?'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='importance',
            field=models.CharField(choices=[('vh', 'Essential'), ('h', 'important'), ('m', 'desirable'), ('l', 'Curiosity/interest'), ('vl', 'trivial'), ('cr', 'circumstantial')], default='m', max_length=2, verbose_name='How vital is this task? Will It bring great benefits if done? Great demerits if not done?'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='progress',
            field=models.CharField(choices=[('nt', 'Not Started'), ('ip', 'In Progress'), ('dn', 'Done'), ('fo', 'forgotten'), ('fn', 'forgotten and not started'), ('hd', 'Hardship')], default='nt', max_length=2, verbose_name="What's the progress on this task?"),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='day',
            field=models.DateField(default='2023-10-20', help_text='Format: year-month-day', verbose_name="the day i (don't) have to do this"),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='end_time',
            field=models.TimeField(default='19:12', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='start_time',
            field=models.TimeField(default='19:11', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
