# Generated by Django 4.1.3 on 2023-11-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0046_alter_dailytask_end_time_alter_dailytask_importance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='short_description',
            new_name='quick_description',
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='end_time',
            field=models.TimeField(default='20:15', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='start_time',
            field=models.TimeField(default='20:14', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='day',
            field=models.DateField(default='2023-11-30', help_text='Format: year-month-day', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='end_time',
            field=models.TimeField(default='20:15', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='eventrepetiton',
            name='start_time',
            field=models.TimeField(default='20:14', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='duration',
            field=models.CharField(choices=[('7', 'Minutes'), ('6', 'Hours'), ('5', 'Days'), ('4', 'Weeks'), ('3', 'Months'), ('2', 'Years'), ('1', 'Perpetual')], default='6', max_length=2, verbose_name='How long do you expect this to take?'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='progress',
            field=models.CharField(choices=[('fn', 'forgotten and not started'), ('nt', 'Not Started'), ('fo', 'forgotten'), ('ip', 'In Progress'), ('hd', 'Hardship'), ('dn', 'Done')], default='nt', max_length=2, verbose_name="What's the progress on this task?"),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='day',
            field=models.DateField(default='2023-11-30', help_text='Format: year-month-day', verbose_name="the day i (don't) have to do this"),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='end_time',
            field=models.TimeField(default='20:15', help_text='Format: hour:minute', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='whattodotoday',
            name='start_time',
            field=models.TimeField(default='20:14', help_text='Format: hour:minute', verbose_name='Starting time'),
        ),
    ]
