# Generated by Django 4.1.3 on 2022-11-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_comments_category_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='Sdescription',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
