# Generated by Django 4.1.3 on 2022-11-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='hBid',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
