# Generated by Django 4.1.3 on 2022-11-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_category_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='followed',
        ),
        migrations.AlterField(
            model_name='category',
            name='auction',
            field=models.ManyToManyField(blank=True, related_name='category', to='auctions.listings'),
        ),
    ]
