# Generated by Django 4.1.3 on 2022-11-22 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_category_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='bidders',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='owner',
        ),
        migrations.DeleteModel(
            name='bids',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.DeleteModel(
            name='listings',
        ),
    ]
