# Generated by Django 4.1.3 on 2022-11-24 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listings_cimage_listings_caution_alter_listings_hbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='hBid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='owner',
            field=models.ForeignKey(default='{{ request.user }}', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
