# Generated by Django 4.1.3 on 2022-11-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listings_hbid_alter_listings_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='hBid',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
