# Generated by Django 4.1.3 on 2022-11-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_description_listings_hbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='initialBid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
