# Generated by Django 4.1.3 on 2022-11-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_category_auction_listings_followed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='cImage',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='caution',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='listings',
            name='hBid',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField()),
        ),
    ]
