# Generated by Django 4.1.3 on 2022-11-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listings_hbidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
